# The remote repository to read the configuration file from. This is required,
# and must be in "org/repo-name" form. Must be a public repository.
remote: BESTSELLER/bulldozer-deployment

# The path to the configuration file in the remote repository. If not set,
# uses the default configuration path.
path: .github/bulldozer.yml

# The branch (or tag, or commit hash) that should be used on the remote
# repository. If not set, uses the default branch of the repository.
# ref: main