CREATE TABLE IF NOT EXISTS "$db_name" ();

ALTER TABLE "$db_name"
ADD COLUMN IF NOT EXISTS id BIGINT PRIMARY KEY,
ADD COLUMN IF NOT EXISTS repo VARCHAR(100) NOT NULL,
ADD COLUMN IF NOT EXISTS owner VARCHAR(100) NOT NULL,
ADD COLUMN IF NOT EXISTS schedule VARCHAR(100) NOT NULL,
ADD COLUMN IF NOT EXISTS lastrun TIMESTAMP;

GRANT CONNECT ON DATABASE "$db_name" TO "$username";
GRANT USAGE ON SCHEMA "$db_name" TO "$username";