package types

type AutoGenerated struct {
	Orbs      map[string]string     `yaml:"orbs"`
	Executors map[string]MyExecutor `yaml:"executors"`
	Jobs      map[string]Build      `yaml:"jobs"`
}

type Docker struct {
	Image   string   `yaml:"image"`
	Command []string `yaml:"command,omitempty"`
}
type MyExecutor struct {
	Docker []Docker `yaml:"docker"`
}
type Build struct {
	Docker []Docker `yaml:"docker"`
}
