version: 2.1
executors:
  gcp_image:
    docker:
      - image: google/cloud-sdk:alpine
  go_image:
    docker:
      - image: cimg/go:1.15
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

orbs:
  secret-injector: bestsellerit/secret-injector@1.3.2

jobs:
  test:
    executor: go_image
    steps:
      - checkout
      - run:
          name: go get
          command: |
            go get ./...
      - run:
          name: install gotestsum
          command: go get -u gotest.tools/gotestsum
      - run:
          name: go test
          command: |
            mkdir junit
            gotestsum --junitfile junit/unit-tests.xml
      - store_test_results:
          path: ~/project/junit
      - run:
          name: go build
          command: |
            GOOS=linux \
            GOARCH=amd64 \
            go build -ldflags="-w -s"
  test-sonar:
    executor: go_image
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Install Sonarqube scanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip -P /tmp/
            cd /tmp/
            unzip sonar-scanner-cli-4.4.0.2170-linux.zip
      - run:
          name: go get
          command: |
            go get ./...
      - run:
          name: go test - sonar
          command: |
            go test ./... -coverprofile=coverage.out
      - run:
          name: Run SonarCloud Scanner
          command: |
            source /tmp/secrets
            export SONAR_SCANNER_OPTS="-Xmx2048m"
            eval /tmp/sonar-scanner-4.4.0.2170-linux/bin/sonar-scanner \
              -Dsonar.projectKey=$K8S_CLUSTER_SONAR_KEY_GH"_"$CIRCLE_PROJECT_REPONAME \
              -Dsonar.projectName=$CIRCLE_PROJECT_REPONAME \
              -Dsonar.organization=$K8S_CLUSTER_SONAR_ORG_GH \
              -Dsonar.sources=. \
              -Dsonar.test.inclusions=**/**_test.go \
              -Dsonar.sources.inclusions=**/**.go \
              -Dsonar.host.url=$K8S_CLUSTER_SONAR_HOST \
              -Dsonar.login=$K8S_CLUSTER_SONAR_LOGIN_GH \
              -Dsonar.links.scm=$CIRCLE_REPOSITORY_URL \
              -Dsonar.go.coverage.reportPaths=coverage.out

  docker-build-n-push:
    docker:
      - image: docker:stable-git
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - setup_remote_docker
      - run:
          name: Push and build image
          command: |
            source /tmp/secrets
            docker login -u $DOCKER_username -p $DOCKER_password $K8S_CLUSTER_docker_registry_url
            docker build \
              -t $K8S_CLUSTER_docker_registry_url/$SHORT/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG \
              -t $K8S_CLUSTER_docker_registry_url/$SHORT/$CIRCLE_PROJECT_REPONAME:latest \
              --build-arg VERSION=$CIRCLE_TAG .
            docker push $K8S_CLUSTER_docker_registry_url/$SHORT/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
            docker push $K8S_CLUSTER_docker_registry_url/$SHORT/$CIRCLE_PROJECT_REPONAME:latest

  deploy:
    docker:
      - image: google/cloud-sdk:alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: gcloud login
          command: |
            source /tmp/secrets
            gcloud auth activate-service-account --key-file=/tmp/cluster_secret.json
      - run:
          name: install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: connect to the cluster
          command: |
            source /tmp/secrets
            gcloud container clusters get-credentials $K8S_CLUSTER_cluster_name --project $K8S_CLUSTER_project_id --zone europe-west4
      - run:
          name: Install envsubt
          command: |
            apk update
            apk add gettext
      - run:
          name: replace strings
          command: |
            source /tmp/secrets
            if [[ ${CIRCLE_BRANCH} = "master" ]] || [[ ${CIRCLE_TAG} =~ ^[0-9]+(\.[0-9]+)*(-.*)*$ ]];
            then
              export DEPLOY_VERSION=''
              export SECRET_VERSION=prod
            else
              export DEPLOY_VERSION=-$CIRCLE_BRANCH
              echo 'export DEPLOY_VERSION="-$CIRCLE_BRANCH"' >> $BASH_ENV
              source ${BASH_ENV}
              export SECRET_VERSION=$CIRCLE_BRANCH
            fi
            envsubst < ./secrets.yml > ./secrets_var.yml && mv ./secrets_var.yml ./secrets.yml
            envsubst < ./deployment.yml > ./deployment_var.yml && mv ./deployment_var.yml ./deployment.yml
      - secret-injector/inject:
          app-name: $CIRCLE_PROJECT_REPONAME$DEPLOY_VERSION
          deploy-file: ./deployment.yml
          secret-file: secrets.yml
      - run:
          name: create kubernetes service
          command: |
            kubectl apply -f ./deployment.yml

  build-push:
    executor: gcp_image
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Build and push image
          command: |
            # source /tmp/secrets

            gcloud auth activate-service-account --key-file=/tmp/cluster_secret.json
            gcloud auth configure-docker europe-docker.pkg.dev
            
            export docker_registry_url=europe-docker.pkg.dev/es-standalone-cb21
            docker build -t $docker_registry_url/es-docker/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
            docker push $docker_registry_url/es-docker/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

  build-push-serverless:
    executor: gcp_image
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: install jq
          command: |
            apk add --no-cache jq
      - run:
          name: Build and push image
          command: |
            # source /tmp/secrets

            gcloud auth activate-service-account --key-file=/tmp/cluster_secret.json
            gcloud auth configure-docker europe-docker.pkg.dev --quiet
            
            export docker_registry_url=europe-docker.pkg.dev/es-standalone-cb21
            docker build -t $docker_registry_url/es-docker/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
            docker push $docker_registry_url/es-docker/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

  deploy-serverless:
    executor: gcp_image
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: install jq
          command: |
            apk add --no-cache jq
      - run:
          name: gcloud login
          command: |
            cat /tmp/cloudrun_admin | jq -r .private_key_data | base64 -d > cloudrun-admin.json
            gcloud auth activate-service-account --key-file=./cloudrun-admin.json
      - run:
          name: create alfeios deployment
          command: |
            gcloud beta run deploy alfeios \
              --image=europe-docker.pkg.dev/es-standalone-cb21/es-docker/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 \
              --allow-unauthenticated \
              --min-instances=1 \
              --max-instances=100 \
              --port=3000 \
              --platform=managed \
              --region=europe-west4 \
              --project=es-standalone-cb21 \
              --set-env-vars VAULT_ADDR="${VAULT_ADDR}",VAULT_ROLE=dependabot-circleci,VAULT_SECRET=ES/data/dependabot-circleci/prod \
              --service-account=dependabot-circleci-dev@es-standalone-dev-ea40.iam.gserviceaccount.com
      # - run:
      #     name: create alfeios domain mapping
      #     command: |
      #       if ! gcloud beta run domain-mappings describe --domain=bestsellerit.com --platform=managed --region=europe-west1 --project=es-standalone-cb21; then
      #         gcloud beta run domain-mappings create \
      #           --service=$CIRCLE_PROJECT_REPONAME \
      #           --domain=bestsellerit.com \
      #           --platform=managed \
      #           --region=europe-west1 \
      #           --project=es-standalone-cb21
      #       fi


workflows:
  test:
    jobs:
      - secret-injector/dump-secrets:
          context: 
            - es02-prod
            - shared
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - test:
          context:
            - shared
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - test-sonar:
          context: 
            - es02-prod
            - shared
          requires:
            - secret-injector/dump-secrets
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
  
  test-build-deploy:
    jobs:
      - secret-injector/dump-secrets:
          context: 
            - es02-prod
            - shared
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - test:
          context:
            - shared
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - test-sonar:
          context: 
            - es02-prod
            - shared
          requires:
            - secret-injector/dump-secrets
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - docker-build-n-push:
          context: 
            - es02-prod
            - shared
          requires:
            - secret-injector/dump-secrets
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - deploy:
          context: 
            - es02-prod
            - shared
          requires:
            - docker-build-n-push
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/

  serverless-test-build-deploy:
    jobs:
      - secret-injector/dump-secrets:
          context: es02-prod
      # - test:
      #     requires:
      #       - secret-injector/dump-secrets
      # - test-sonar:
      #     requires:
      #       - secret-injector/dump-secrets

      - secret-injector/dump-secrets:
          # requires:
            # - test
            # - test-sonar
          name: secret-injector/cloudrun
          vault-path: "gcp_landingzone/key/cloudrun-admin"
          output-filename: cloudrun_admin
          format: json
          context: es02-prod
          filters:
            branches:
              only: ES-1219_cloud_run
      - build-push-serverless:
          requires:
            - secret-injector/dump-secrets
            - secret-injector/cloudrun
          filters:
            branches:
              only: ES-1219_cloud_run
      - deploy-serverless:
          requires:
            - build-push-serverless
          filters:
            branches:
              only: ES-1219_cloud_run

