version: 2.1

orbs:
  secret-injector: bestsellerit/secret-injector@1.7.5
  cci-common: bestsellerit/cci-common@1.4.2

workflows:
  test:
    jobs:
      - secret-injector/dump-secrets:
          context:
            - es02-prod
            - shared
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - cci-common/go_test_unit:
          context:
            - shared
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - cci-common/go_test_sonar:
          context:
            - es02-prod
            - shared
          requires:
            - secret-injector/dump-secrets
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - cci-common/build_n_push_docker:
          dry_run: true
          requires:
            - secret-injector/dump-secrets
          context:
            - es02-prod
            - shared
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/

  serverless-test-build-deploy:
    jobs:
      - secret-injector/dump-secrets-yaml:
          secret-file: ci-secrets.yaml
          context:
            - es02-prod
            - shared
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - cci-common/build_n_push_docker:
          tag: ${CIRCLE_TAG}
          requires:
            - secret-injector/dump-secrets-yaml
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - cci-common/terraform_plan:
          path: ./terraform
          args: '-var tag=${CIRCLE_TAG}'
          context:
            - es02-prod
            - shared
          requires:
            - cci-common/build_n_push_docker
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - cci-common/terraform_apply:
          path: ./terraform
          context:
            - es02-prod
            - shared
          requires:
            - cci-common/terraform_plan
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/


