version: 2.1

orbs:
  secret-injector: bestsellerit/secret-injector@1.7.5
  cci-common: bestsellerit/cci-common@1.4.3
  google-sql-operations: bestsellerit/google-sql-operations@1.5.1

workflows:
  test:
    jobs:
      - secret-injector/dump-secrets-yaml:
          secret-file: ci-secrets.yaml
          context:
            - es02-prod
            - shared
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - cci-common/go_test_unit:
          context:
            - shared
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - cci-common/go_test_sonar:
          context:
            - es02-prod
            - shared
          requires:
            - secret-injector/dump-secrets-yaml
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - cci-common/build_n_push_docker:
          dry_run: true
          requires:
            - secret-injector/dump-secrets-yaml
          context:
            - es02-prod
            - shared
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
      - cci-common/terraform_plan:
          path: ./terraform
          args: '-var tag=1.0.0'
          lock: false
          context:
            - es02-prod
            - shared
          requires:
            - secret-injector/dump-secrets-yaml
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
          pre-steps:
            - attach_workspace:
                at: /tmp
            - run:
                command: |
                  cat /tmp/cloudrun_admin | jq -r .private_key_data | base64 -d > /tmp/cloudrun-admin.json

  deploy:
    jobs:
      - secret-injector/dump-secrets-yaml:
          secret-file: ci-secrets.yaml
          context:
            - es02-prod
            - shared
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - cci-common/build_n_push_docker:
          tag: ${CIRCLE_TAG}
          repo: public-docker
          context:
            - es02-prod
            - shared
          requires:
            - secret-injector/dump-secrets-yaml
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - cci-common/terraform_plan:
          path: ./terraform
          args: '-var tag=${CIRCLE_TAG}'
          context:
            - es02-prod
            - shared
          requires:
            - cci-common/build_n_push_docker
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
          pre-steps:
            - attach_workspace:
                at: /tmp
            - run:
                command: |
                  cat /tmp/cloudrun_admin | jq -r .private_key_data | base64 -d > /tmp/cloudrun-admin.json
              - persist_to_workspace:
                root: /tmp
                paths:
                  - /tmp/cloudrun-admin.json
      - cci-common/terraform_apply:
          path: ./terraform
          context:
            - es02-prod
            - shared
          requires:
            - cci-common/terraform_plan
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - google-sql-operations/init-db:
          instance: $instance
          db-name: $db_name
          username: $username
          password: $password
          gcloud-service-account: /tmp/cloudrun-admin.json
          post-script: ./init.sql
          project: dependabot-pub-prod-586e
          context:
            - es02-prod
            - shared
          requires:
            - cci-common/terraform_apply
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/